import random

from cl_data.src.constants import PretrainTasks
from cl_data.src.random_value_generator import RandomValueGenerator
from cl_data.src.utility import Utility


def get_batch_fifteen_example_paragraph():
    a = RandomValueGenerator.generate_random_integer(-10, 100)
    b = RandomValueGenerator.generate_random_integer(-10, 100)
    x = random.uniform(-10.0, 100.0)
    y = random.uniform(-10.0, 100.0)
    z = random.uniform(-1.0, 1.0)
    random_int_one = RandomValueGenerator.generate_random_integer()
    random_int_two = random_int_one + RandomValueGenerator.generate_random_integer()
    random_int_three = random_int_two + RandomValueGenerator.generate_random_integer()
    random_int_four = RandomValueGenerator.generate_random_integer()
    random_float = RandomValueGenerator.generate_random_float()
    random_bool = RandomValueGenerator.generate_random_boolean()
    random_list = Utility.remove_spaces(
        str(RandomValueGenerator.generate_random_list())
    )
    lst_str = ", ".join(str(num) for num in random_list)

    examples = [
        [
            f"Calculating the value of {a}^3 - {b}^3 = ##a_cubed_minus_b_cubed({a}, {b})",
            f"a_cubed_minus_b_cubed({a}, {b}) = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The result of evaluating {a}^3 - {b}^3 = ##a_cubed_minus_b_cubed({a}, {b})",
            f"Calculation: a_cubed_minus_b_cubed({a}, {b}) = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The expression {a}^3 - {b}^3 = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The outcome of evaluating a_cubed_minus_b_cubed({a}, {b}) = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The result obtained by calculating {a}^3 - {b}^3 = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The value of {a} cubed minus {b} cubed = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The computed result of evaluating {a}^3 - {b}^3 = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The difference between {a} cubed and {b} cubed = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The outcome of determining {a}^3 - {b}^3 = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The numerical value of {a} cubed minus {b} cubed = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The result of evaluating a_cubed_minus_b_cubed({a}, {b}) = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The value of {a}^3 - {b}^3 is = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The result derived from evaluating a_cubed_minus_b_cubed({a}, {b}) = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The calculated result of {a} cubed minus {b} cubed = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The value of {a} cubed minus {b} cubed is = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The value of {a}^3 minus {b}^3 equals = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The value of {a}^3 minus {b}^3 is = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The computed value of {a}^3 - {b}^3 = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The calculated outcome of {a} cubed minus {b} cubed = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The outcome of evaluating a_cubed_minus_b_cubed({a}, {b}) = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The outcome of determining the difference between {a} cubed and {b} cubed = ##a_cubed_minus_b_cubed({a}, {b})",
            f"The outcome of evaluating a_cubed_minus_b_cubed({a}, {b}) = ##a_cubed_minus_b_cubed({a}, {b})",
        ],
        [
            f"Calculating the value of {a}^3 + {b}^3 = ##a_cubed_plus_b_cubed({a}, {b})",
            f"a_cubed_plus_b_cubed({a}, {b}) = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The result of evaluating {a}^3 + {b}^3 = ##a_cubed_plus_b_cubed({a}, {b})",
            f"Calculation: a_cubed_plus_b_cubed({a}, {b}) = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The expression {a}^3 + {b}^3 = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The outcome of evaluating a_cubed_plus_b_cubed({a}, {b}) = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The result obtained by calculating {a}^3 + {b}^3 = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The value of {a} cubed plus {b} cubed = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The computed result of evaluating {a}^3 + {b}^3 = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The sum of {a} cubed and {b} cubed = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The outcome of determining {a}^3 + {b}^3 = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The numerical value of {a} cubed plus {b} cubed = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The result of evaluating a_cubed_plus_b_cubed({a}, {b}) = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The value of {a}^3 + {b}^3 is = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The result derived from evaluating a_cubed_plus_b_cubed({a}, {b}) = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The calculated result of {a} cubed plus {b} cubed = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The value of {a} cubed plus {b} cubed is = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The value of {a}^3 plus {b}^3 equals = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The value of {a}^3 plus {b}^3 is = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The computed value of {a}^3 + {b}^3 = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The calculated outcome of {a} cubed plus {b} cubed = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The outcome of evaluating a_cubed_plus_b_cubed({a}, {b}) = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The outcome of determining the sum of {a} cubed and {b} cubed = ##a_cubed_plus_b_cubed({a}, {b})",
            f"The outcome of evaluating a_cubed_plus_b_cubed({a}, {b}) = ##a_cubed_plus_b_cubed({a}, {b})",
        ],
        [
            f"Calculating the value of ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b}) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The result of evaluating ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"Calculation: a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b}) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The expression ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b}) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The result obtained by calculating ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} - {b}) times ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The computed result of evaluating ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The product of ({a} - {b}) and ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The outcome of determining ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The numerical value of ({a} - {b}) times ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The result of evaluating a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b}) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) is = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The result derived from evaluating a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b}) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The calculated result of ({a} - {b}) times ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} - {b}) times ({a}^2 + {a} * {b} + {b}^2) is = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) equals = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) is = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The computed value of ({a} - {b}) * ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The calculated outcome of ({a} - {b}) times ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b}) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The outcome of determining the product of ({a} - {b}) and ({a}^2 + {a} * {b} + {b}^2) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b}) = ##a_minus_b_times_a_squared_plus_ab_plus_b_squared({a}, {b})",
        ],
        [
            f"Calculating the value of ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The result of evaluating ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"Calculation: a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The expression ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The result obtained by calculating ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The value of ({a} - {b}) cubed plus 3 times {a} times {b} times ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The computed result of evaluating ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The sum of ({a} - {b}) cubed and 3 times {a} times {b} times ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The outcome of determining ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The numerical value of ({a} - {b}) cubed plus 3 times {a} times {b} times ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The result of evaluating a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The value of ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) is = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The result derived from evaluating a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The calculated result of ({a} - {b}) cubed plus 3 times {a} times {b} times ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The value of ({a} - {b}) cubed plus 3 times {a} times {b} times ({a} - {b}) is = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The value of ({a} - {b})^3 plus 3 times {a} times {b} times ({a} - {b}) equals = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The value of ({a} - {b})^3 plus 3 times {a} times {b} times ({a} - {b}) is = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The computed value of ({a} - {b})^3 + 3 * {a} * {b} * ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The calculated outcome of ({a} - {b}) cubed plus 3 times {a} times {b} times ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The outcome of determining the sum of ({a} - {b}) cubed and 3 times {a} times {b} times ({a} - {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b}) = ##a_minus_b_whole_cubed_plus_3ab_times_a_minus_b({a}, {b})",
        ],
        [
            f"Calculating the value of ({a} - {b})^2 = ##a_minus_b_whole_squared({a}, {b})",
            f"a_minus_b_whole_squared({a}, {b}) = ##a_minus_b_whole_squared({a}, {b})",
            f"The result of evaluating ({a} - {b})^2 = ##a_minus_b_whole_squared({a}, {b})",
            f"Calculation: a_minus_b_whole_squared({a}, {b}) = ##a_minus_b_whole_squared({a}, {b})",
            f"The expression ({a} - {b})^2 = ##a_minus_b_whole_squared({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_squared({a}, {b}) = ##a_minus_b_whole_squared({a}, {b})",
            f"The result obtained by calculating ({a} - {b})^2 = ##a_minus_b_whole_squared({a}, {b})",
            f"The value of ({a} - {b}) squared = ##a_minus_b_whole_squared({a}, {b})",
            f"The computed result of evaluating ({a} - {b})^2 = ##a_minus_b_whole_squared({a}, {b})",
            f"The outcome of determining ({a} - {b})^2 = ##a_minus_b_whole_squared({a}, {b})",
            f"The numerical value of ({a} - {b}) squared = ##a_minus_b_whole_squared({a}, {b})",
            f"The result of evaluating a_minus_b_whole_squared({a}, {b}) = ##a_minus_b_whole_squared({a}, {b})",
            f"The value of ({a} - {b})^2 is = ##a_minus_b_whole_squared({a}, {b})",
            f"The result derived from evaluating a_minus_b_whole_squared({a}, {b}) = ##a_minus_b_whole_squared({a}, {b})",
            f"The calculated result of ({a} - {b}) squared = ##a_minus_b_whole_squared({a}, {b})",
            f"The value of ({a} - {b}) squared is = ##a_minus_b_whole_squared({a}, {b})",
            f"The value of ({a} - {b})^2 equals = ##a_minus_b_whole_squared({a}, {b})",
            f"The value of ({a} - {b})^2 is = ##a_minus_b_whole_squared({a}, {b})",
            f"The computed value of ({a} - {b})^2 = ##a_minus_b_whole_squared({a}, {b})",
            f"The calculated outcome of ({a} - {b}) squared = ##a_minus_b_whole_squared({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_squared({a}, {b}) = ##a_minus_b_whole_squared({a}, {b})",
            f"The outcome of determining the value of ({a} - {b}) squared = ##a_minus_b_whole_squared({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_squared({a}, {b}) = ##a_minus_b_whole_squared({a}, {b})",
        ],
        [
            f"Calculating the value of ({a} - {b})^2 + 4*{a}*{b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"a_minus_b_whole_squared_plus_4ab({a}, {b}) = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The result of evaluating ({a} - {b})^2 + 4*{a}*{b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"Calculation: a_minus_b_whole_squared_plus_4ab({a}, {b}) = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The expression ({a} - {b})^2 + 4*{a}*{b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_squared_plus_4ab({a}, {b}) = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The result obtained by calculating ({a} - {b})^2 + 4*{a}*{b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The value of ({a} - {b}) squared plus 4 times {a} times {b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The computed result of evaluating ({a} - {b})^2 + 4*{a}*{b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The sum of ({a} - {b}) squared and 4 times {a} times {b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The outcome of determining ({a} - {b})^2 + 4*{a}*{b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The numerical value of ({a} - {b}) squared plus 4 times {a} times {b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The result of evaluating a_minus_b_whole_squared_plus_4ab({a}, {b}) = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The value of ({a} - {b})^2 + 4*{a}*{b} is = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The result derived from evaluating a_minus_b_whole_squared_plus_4ab({a}, {b}) = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The calculated result of ({a} - {b}) squared plus 4 times {a} times {b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The calculated sum of ({a} - {b}) squared and 4 times {a} times {b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The value of ({a} - {b})^2 + 4*{a}*{b} equals = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The value of ({a} - {b})^2 plus 4 times {a} times {b} is = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The value of ({a} - {b}) squared plus 4 times {a} times {b} is = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The computed value of ({a} - {b})^2 + 4*{a}*{b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The calculated outcome of ({a} - {b}) squared plus 4 times {a} times {b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_squared_plus_4ab({a}, {b}) = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The outcome of calculating the sum of ({a} - {b}) squared and 4 times {a} times {b} = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
            f"The outcome of evaluating a_minus_b_whole_squared_plus_4ab({a}, {b}) = ##a_minus_b_whole_squared_plus_4ab({a}, {b})",
        ],
        [
            f"Calculating the value of ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b}) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The result of evaluating ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"Calculation: a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b}) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The expression ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b}) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The result obtained by calculating ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} + {b}) times ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The computed result of evaluating ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The product of ({a} + {b}) and ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The outcome of determining ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The numerical value of ({a} + {b}) times ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The result of evaluating a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b}) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) is = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The result derived from evaluating a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b}) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The calculated result of ({a} + {b}) times ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} + {b}) times ({a}^2 - {a} * {b} + {b}^2) is = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) equals = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The value of ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) is = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The computed value of ({a} + {b}) * ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The calculated outcome of ({a} + {b}) times ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b}) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The outcome of determining the product of ({a} + {b}) and ({a}^2 - {a} * {b} + {b}^2) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b}) = ##a_plus_b_times_a_squared_minus_ab_plus_b_squared({a}, {b})",
        ],
        [
            f"Calculating the value of ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The result of evaluating ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"Calculation: a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The expression ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The result obtained by calculating ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The value of ({a} + {b}) cubed minus 3 times {a} times {b} times ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The computed result of evaluating ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The difference between ({a} + {b}) cubed and 3 times {a} times {b} times ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The outcome of determining ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The numerical value of ({a} + {b}) cubed minus 3 times {a} times {b} times ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The result of evaluating a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The value of ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) is = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The result derived from evaluating a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The calculated result of ({a} + {b}) cubed minus 3 times {a} times {b} times ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The value of ({a} + {b}) cubed minus 3 times {a} times {b} times ({a} + {b}) is = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The value of ({a} + {b})^3 minus 3 times {a} times {b} times ({a} + {b}) equals = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The value of ({a} + {b})^3 minus 3 times {a} times {b} times ({a} + {b}) is = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The computed value of ({a} + {b})^3 - 3 * {a} * {b} * ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The calculated outcome of ({a} + {b}) cubed minus 3 times {a} times {b} times ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The outcome of determining the difference between ({a} + {b}) cubed and 3 times {a} times {b} times ({a} + {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b}) = ##a_plus_b_whole_cubed_minus_3ab_times_a_plus_b({a}, {b})",
        ],
        [
            f"Calculating the square of the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"a_plus_b_whole_square({a}, {b}) = ##a_plus_b_whole_square({a}, {b})",
            f"The result of squaring the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"Calculation: a_plus_b_whole_square({a}, {b}) = ##a_plus_b_whole_square({a}, {b})",
            f"The square of the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_square({a}, {b}) = ##a_plus_b_whole_square({a}, {b})",
            f"The result obtained by squaring the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The square value of {a} plus {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The computed result of calculating the square of the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The square of the sum of the numbers {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The outcome of determining the square of the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The numerical value of squaring {a} plus {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The result of evaluating a_plus_b_whole_square({a}, {b}) = ##a_plus_b_whole_square({a}, {b})",
            f"The square of the sum of {a} and {b} equals = ##a_plus_b_whole_square({a}, {b})",
            f"The result derived from evaluating a_plus_b_whole_square({a}, {b}) = ##a_plus_b_whole_square({a}, {b})",
            f"The squared value of {a} plus {b} is = ##a_plus_b_whole_square({a}, {b})",
            f"The value of squaring {a} plus {b} is = ##a_plus_b_whole_square({a}, {b})",
            f"The computed square of the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The calculated result of calculating the square of the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The square value of {a} added to {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The computed value of squaring the sum of {a} and {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_square({a}, {b}) = ##a_plus_b_whole_square({a}, {b})",
            f"The outcome of determining the squared value of {a} plus {b} = ##a_plus_b_whole_square({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_square({a}, {b}) = ##a_plus_b_whole_square({a}, {b})",
        ],
        [
            f"Calculating the value of ({a} + {b})^2 - 4*{a}*{b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"a_plus_b_whole_squared_minus_4ab({a}, {b}) = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The result of evaluating ({a} + {b})^2 - 4*{a}*{b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"Calculation: a_plus_b_whole_squared_minus_4ab({a}, {b}) = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The expression ({a} + {b})^2 - 4*{a}*{b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_squared_minus_4ab({a}, {b}) = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The result obtained by calculating ({a} + {b})^2 - 4*{a}*{b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The value of ({a} + {b}) squared minus 4 times {a} times {b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The computed result of evaluating ({a} + {b})^2 - 4*{a}*{b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The sum of ({a} + {b}) squared and -4 times {a} times {b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The outcome of determining ({a} + {b})^2 - 4*{a}*{b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The numerical value of ({a} + {b}) squared minus 4 times {a} times {b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The result of evaluating a_plus_b_whole_squared_minus_4ab({a}, {b}) = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The value of ({a} + {b})^2 - 4*{a}*{b} is = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The result derived from evaluating a_plus_b_whole_squared_minus_4ab({a}, {b}) = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The calculated result of ({a} + {b}) squared minus 4 times {a} times {b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The calculated sum of ({a} + {b}) squared and -4 times {a} times {b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The value of ({a} + {b})^2 - 4*{a}*{b} equals = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The value of ({a} + {b})^2 minus 4 times {a} times {b} is = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The value of ({a} + {b}) squared minus 4 times {a} times {b} is = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The computed value of ({a} + {b})^2 - 4*{a}*{b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The calculated outcome of ({a} + {b}) squared minus 4 times {a} times {b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_squared_minus_4ab({a}, {b}) = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The outcome of determining the sum of ({a} + {b}) squared and -4 times {a} times {b} = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
            f"The outcome of evaluating a_plus_b_whole_squared_minus_4ab({a}, {b}) = ##a_plus_b_whole_squared_minus_4ab({a}, {b})",
        ],
        [
            f"Calculating the value of {a}^2 - 2*{a}*{b} + {b}^2 = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"a_squared_minus_2ab_plus_b_squared({a}, {b}) = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The result of evaluating {a}^2 - 2*{a}*{b} + {b}^2 = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"Calculation: a_squared_minus_2ab_plus_b_squared({a}, {b}) = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The expression {a}^2 - 2*{a}*{b} + {b}^2 = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_minus_2ab_plus_b_squared({a}, {b}) = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The result obtained by calculating {a}^2 - 2*{a}*{b} + {b}^2 = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a} squared minus 2 times {a} times {b} plus {b} squared = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The computed result of evaluating {a}^2 - 2*{a}*{b} + {b}^2 = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The sum of {a} squared, -2 times {a} times {b}, and {b} squared = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of determining {a}^2 - 2*{a}*{b} + {b}^2 = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The numerical value of {a} squared minus 2 times {a} times {b} plus {b} squared = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The result of evaluating a_squared_minus_2ab_plus_b_squared({a}, {b}) = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a}^2 - 2*{a}*{b} + {b}^2 is = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The result derived from evaluating a_squared_minus_2ab_plus_b_squared({a}, {b}) = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The calculated result of {a} squared minus 2 times {a} times {b} plus {b} squared = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The calculated sum of {a} squared, -2 times {a} times {b}, and {b} squared = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a}^2 - 2*{a}*{b} + {b}^2 equals = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a}^2 minus 2 times {a} times {b} plus {b}^2 is = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a} squared minus 2 times {a} times {b} plus {b} squared is = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The computed value of {a}^2 - 2*{a}*{b} + {b}^2 = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The calculated outcome of {a} squared minus 2 times {a} times {b} plus {b} squared = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_minus_2ab_plus_b_squared({a}, {b}) = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of determining the sum of {a} squared, -2 times {a} times {b}, and {b} squared = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_minus_2ab_plus_b_squared({a}, {b}) = ##a_squared_minus_2ab_plus_b_squared({a}, {b})",
        ],
        [
            f"Calculating the value of {a}^2 + 2*{a}*{b} + {b}^2 = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"a_squared_plus_2ab_plus_b_squared({a}, {b}) = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The result of evaluating {a}^2 + 2*{a}*{b} + {b}^2 = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"Calculation: a_squared_plus_2ab_plus_b_squared({a}, {b}) = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The expression {a}^2 + 2*{a}*{b} + {b}^2 = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_plus_2ab_plus_b_squared({a}, {b}) = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The result obtained by calculating {a}^2 + 2*{a}*{b} + {b}^2 = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a} squared plus 2 times {a} times {b} plus {b} squared = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The computed result of evaluating {a}^2 + 2*{a}*{b} + {b}^2 = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The sum of {a} squared, 2 times {a} times {b}, and {b} squared = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of determining {a}^2 + 2*{a}*{b} + {b}^2 = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The numerical value of {a} squared plus 2 times {a} times {b} plus {b} squared = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The result of evaluating a_squared_plus_2ab_plus_b_squared({a}, {b}) = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a}^2 + 2*{a}*{b} + {b}^2 is = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The result derived from evaluating a_squared_plus_2ab_plus_b_squared({a}, {b}) = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The calculated result of {a} squared plus 2 times {a} times {b} plus {b} squared = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The calculated sum of {a} squared, 2 times {a} times {b}, and {b} squared = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a}^2 + 2*{a}*{b} + {b}^2 equals = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a}^2 plus 2 times {a} times {b} plus {b}^2 is = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The value of {a} squared plus 2 times {a} times {b} plus {b} squared is = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The computed value of {a}^2 + 2*{a}*{b} + {b}^2 = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The calculated outcome of {a} squared plus 2 times {a} times {b} plus {b} squared = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_plus_2ab_plus_b_squared({a}, {b}) = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of calculating the sum of {a} squared, 2 times {a} times {b}, and {b} squared = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_plus_2ab_plus_b_squared({a}, {b}) = ##a_squared_plus_2ab_plus_b_squared({a}, {b})",
        ],
        [
            f"Calculating the value of {a}^2 + {b}^2 = ##a_squared_plus_b_squared({a}, {b})",
            f"a_squared_plus_b_squared({a}, {b}) = ##a_squared_plus_b_squared({a}, {b})",
            f"The result of evaluating {a}^2 + {b}^2 = ##a_squared_plus_b_squared({a}, {b})",
            f"Calculation: a_squared_plus_b_squared({a}, {b}) = ##a_squared_plus_b_squared({a}, {b})",
            f"The expression {a}^2 + {b}^2 = ##a_squared_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_plus_b_squared({a}, {b}) = ##a_squared_plus_b_squared({a}, {b})",
            f"The result obtained by calculating {a}^2 + {b}^2 = ##a_squared_plus_b_squared({a}, {b})",
            f"The value of {a} squared plus {b} squared = ##a_squared_plus_b_squared({a}, {b})",
            f"The computed result of evaluating {a}^2 + {b}^2 = ##a_squared_plus_b_squared({a}, {b})",
            f"The sum of {a} squared and {b} squared = ##a_squared_plus_b_squared({a}, {b})",
            f"The outcome of determining {a}^2 + {b}^2 = ##a_squared_plus_b_squared({a}, {b})",
            f"The numerical value of {a} squared plus {b} squared = ##a_squared_plus_b_squared({a}, {b})",
            f"The result of evaluating a_squared_plus_b_squared({a}, {b}) = ##a_squared_plus_b_squared({a}, {b})",
            f"The value of {a}^2 + {b}^2 is = ##a_squared_plus_b_squared({a}, {b})",
            f"The result derived from evaluating a_squared_plus_b_squared({a}, {b}) = ##a_squared_plus_b_squared({a}, {b})",
            f"The calculated result of {a} squared plus {b} squared = ##a_squared_plus_b_squared({a}, {b})",
            f"The value of {a} squared plus {b} squared is = ##a_squared_plus_b_squared({a}, {b})",
            f"The value of {a}^2 plus {b}^2 equals = ##a_squared_plus_b_squared({a}, {b})",
            f"The value of {a}^2 plus {b}^2 is = ##a_squared_plus_b_squared({a}, {b})",
            f"The computed value of {a}^2 + {b}^2 = ##a_squared_plus_b_squared({a}, {b})",
            f"The calculated outcome of {a} squared plus {b} squared = ##a_squared_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_plus_b_squared({a}, {b}) = ##a_squared_plus_b_squared({a}, {b})",
            f"The outcome of determining the sum of {a} squared and {b} squared = ##a_squared_plus_b_squared({a}, {b})",
            f"The outcome of evaluating a_squared_plus_b_squared({a}, {b}) = ##a_squared_plus_b_squared({a}, {b})",
        ],
        [
            f"The absolute difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"absolute_difference({x}, {y}) = ##absolute_difference({x}, {y})",
            f"The positive value of the difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"Calculation: absolute_difference({x}, {y}) = ##absolute_difference({x}, {y})",
            f"The distance between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The non-negative value of the difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The absolute value of the subtraction of {x} from {y} = ##absolute_difference({x}, {y})",
            f"The magnitude of the difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The result of calculating the absolute difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The absolute positive value of the subtraction of {y} from {x} = ##absolute_difference({x}, {y})",
            f"The value of the absolute difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The result of finding the absolute difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The positive distance between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The absolute value of the difference of {x} minus {y} = ##absolute_difference({x}, {y})",
            f"The magnitude of the subtraction of {x} from {y} is = ##absolute_difference({x}, {y})",
            f"The absolute value of the difference between {x} and {y} is = ##absolute_difference({x}, {y})",
            f"The value of the absolute positive difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The absolute magnitude of the difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The result of finding the non-negative difference between {x} and {y} = ##absolute_difference({x}, {y})",
            f"The value of the absolute difference of {x} minus {y} = ##absolute_difference({x}, {y})",
            f"The positive absolute difference between {x} and {y} is = ##absolute_difference({x}, {y})",
            f"The result of calculating absolute_difference({x}, {y}) is = ##absolute_difference({x}, {y})",
            f"The magnitude of the absolute difference between {x} and {y} is = ##absolute_difference({x}, {y})",
            f"The absolute result of {x} minus {y} is = ##absolute_difference({x}, {y})",
            f"The positive absolute value of the difference between {x} and {y} is = ##absolute_difference({x}, {y})",
        ],
        [
            f"The absolute value of the number {x} = ##absolute({x})",
            f"absolute({x}) = ##absolute({x})",
            f"The result of taking the absolute value of {x} = ##absolute({x})",
            f"Calculation: absolute({x}) = ##absolute({x})",
            f"The magnitude of the number {x} = ##absolute({x})",
            f"The non-negative value of {x} = ##absolute({x})",
            f"The outcome of calculating the absolute value of {x} = ##absolute({x})",
            f"The absolute magnitude of {x} = ##absolute({x})",
            f"The result of evaluating the absolute value of {x} = ##absolute({x})",
            f"The value obtained by removing the sign of {x} = ##absolute({x})",
            f"The absolute value of the quantity {x} = ##absolute({x})",
            f"The absolute result of the number {x} = ##absolute({x})",
            f"The outcome of finding the absolute value of {x} = ##absolute({x})",
            f"The computed value of absolute({x}) is = ##absolute({x})",
            f"The value obtained by discarding the sign of {x} is = ##absolute({x})",
            f"The result of evaluating the magnitude of {x} = ##absolute({x})",
            f"The absolute outcome of the number {x} is = ##absolute({x})",
            f"The value of {x} without its sign is = ##absolute({x})",
            f"The computed absolute value of {x} is = ##absolute({x})",
            f"The non-negative result of evaluating the expression {x} = ##absolute({x})",
            f"The absolute value of {x} is = ##absolute({x})",
            f"The value of the number {x} without its sign is = ##absolute({x})",
            f"The calculated absolute value of {x} is = ##absolute({x})",
            f"The result of taking the absolute magnitude of {x} is = ##absolute({x})",
            f"The outcome of finding the absolute magnitude of {x} is = ##absolute({x})",
            f"The absolute result of evaluating {x} is = ##absolute({x})",
        ],
        [
            f"Adding {a} plus {b} = ##addition({a},{b})",
            f"{a} + {b} = ##addition({a},{b})",
            f"Summing {a} with {b} ... = ##addition({a},{b})",
            f"The result of adding {a} and {b} = ##addition({a},{b})",
            f"{a} plus {b} equals? = ##addition({a},{b})",
            f"Calculation: {a} + {b} = ##addition({a},{b})",
            f"{a} plus {b} is? = ##addition({a},{b})",
            f"Summing up {a} and {b} = ##addition({a},{b})",
            f"{a} combined with {b} = ##addition({a},{b})",
            f"The sum of {a} and {b} = ##addition({a},{b})",
            f"{a} + {b} = = ##addition({a},{b})",
            f"The total of {a} and {b} = ##addition({a},{b})",
            f"Sum: {a} + {b} = ##addition({a},{b})",
            f"{a} and {b} added together = ##addition({a},{b})",
            f"{a} + {b} results in = ##addition({a},{b})"
        ],
        [
            f"The arccosine of {z} = ##arccosine({z})",
            f"arccos({z}) = ##arccosine({z})",
            f"The angle whose cosine is {z} = ##arccosine({z})",
            f"Calculation: arccos({z}) = ##arccosine({z})",
            f"The inverse cosine function applied to {z} = ##arccosine({z})",
            f"The arccosine value for {z} is = ##arccosine({z})",
            f"The angle whose cosine is equal to {z} = ##arccosine({z})",
            f"The trigonometric function that gives the angle whose cosine is {z} = ##arccosine({z})",
            f"The inverse of the cosine function for the value {z} = ##arccosine({z})",
            f"The result of applying the arccosine function to {z} = ##arccosine({z})",
            f"The angle in degrees with cosine value {z} = ##arccosine({z})",
            f"The angle whose cosine value is {z} degrees = ##arccosine({z})",
            f"The value of the inverse cosine function for {z} = ##arccosine({z})",
            f"The angle that corresponds to a cosine of {z} = ##arccosine({z})",
            f"The angle whose cosine equals {z} = ##arccosine({z})",
            f"The angle for which the cosine value is {z} = ##arccosine({z})",
            f"The angle whose cosine is given by {z} = ##arccosine({z})",
        ],
        [
            f"The arcsine of {z} = ##arcsine({z})",
            f"arcsine({z}) = ##arcsine({z})",
            f"The angle whose sine is {z} = ##arcsine({z})",
            f"Calculation: arcsine({z}) = ##arcsine({z})",
            f"The inverse sine function applied to {z} = ##arcsine({z})",
            f"The arcsine value for {z} is = ##arcsine({z})",
            f"The angle whose sine is equal to {z} = ##arcsine({z})",
            f"The trigonometric function that gives the angle whose sine is {z} = ##arcsine({z})",
            f"The inverse of the sine function for the value {z} = ##arcsine({z})",
            f"The result of applying the arcsine function to {z} = ##arcsine({z})",
            f"The angle in degrees with sine value {z} = ##arcsine({z})",
            f"The angle whose sine value is {z} degrees = ##arcsine({z})",
            f"The value of the inverse sine function for {z} = ##arcsine({z})",
            f"The angle that corresponds to a sine of {z} = ##arcsine({z})",
            f"The angle whose sine equals {z} = ##arcsine({z})",
            f"The angle for which sin(angle) = {z} = ##arcsine({z})",
            f"The angle in radians such that sin(angle) = {z} = ##arcsine({z})",
            f"The angle for which the sine value is {z} = ##arcsine({z})",
            f"The angle whose sine is given by {z} = ##arcsine({z})",
        ],
        [
            f"The arctangent of {z} = ##arctangent({z})",
            f"arctan({z}) = ##arctangent({z})",
            f"The angle whose tangent is {z} = ##arctangent({z})",
            f"Calculation: arctan({z}) = ##arctangent({z})",
            f"The inverse tangent function applied to {z} = ##arctangent({z})",
            f"The arctangent value for {z} is = ##arctangent({z})",
            f"The angle whose tangent is equal to {z} = ##arctangent({z})",
            f"The trigonometric function that gives the angle whose tangent is {z} = ##arctangent({z})",
            f"The inverse of the tangent function for the value {z} = ##arctangent({z})",
            f"The result of applying the arctangent function to {z} = ##arctangent({z})",
            f"The angle in degrees with tangent value {z} = ##arctangent({z})",
            f"The angle whose tangent value is {z} degrees = ##arctangent({z})",
            f"The value of the inverse tangent function for {z} = ##arctangent({z})",
            f"The angle that corresponds to a tangent of {z} = ##arctangent({z})",
            f"The angle whose tangent equals {z} = ##arctangent({z})",
            f"The angle for which tan(angle) = {z} = ##arctangent({z})",
            f"The angle in radians such that tan(angle) = {z} = ##arctangent({z})",
            f"The angle for which the tangent value is {z} = ##arctangent({z})",
            f"The angle whose tangent is given by {z} = ##arctangent({z})",
            f"The angle for which tan(angle) is {z} = ##arctangent({z})",
            f"The angle whose tangent is represented by {z} = ##arctangent({z})",
            f"The angle whose tangent is expressed as {z} = ##arctangent({z})",
            f"The angle whose tangent yields {z} = ##arctangent({z})",
            f"The angle in degrees such that tan(angle) = {z} = ##arctangent({z})",
            f"The inverse tangent function output for {z} = ##arctangent({z})",
            f"The value of the arctangent function at {z} = ##arctangent({z})",
        ],
        [
            f"The list {lst_str} sorted in ascending order = ##ascending_sort({random_list})",
            f"ascending_sort({lst_str}) = ##ascending_sort({random_list})",
            f"The sorted version of the list {lst_str} = ##ascending_sort({random_list})",
            f"Calculation: ascending_sort({lst_str}) = ##ascending_sort({random_list})",
            f"The list {lst_str} arranged in increasing order = ##ascending_sort({random_list})",
            f"The outcome of sorting the elements in the list {lst_str} = ##ascending_sort({random_list})",
            f"The result of arranging the numbers in {lst_str} in ascending order = ##ascending_sort({random_list})",
            f"The list {lst_str} organized in ascending sequence = ##ascending_sort({random_list})",
            f"The sorted list of numbers {lst_str} = ##ascending_sort({random_list})",
            f"The list {lst_str} sorted from least to greatest = ##ascending_sort({random_list})",
            f"The result of sorting the elements of the list {lst_str} = ##ascending_sort({random_list})",
            f"The computed result of sorting {lst_str} in ascending order = ##ascending_sort({random_list})",
            f"The result of evaluating ascending_sort({lst_str}) = ##ascending_sort({random_list})",
            f"The ordered sequence of numbers in the list {lst_str} = ##ascending_sort({random_list})",
            f"The outcome of arranging the elements {lst_str} in ascending order = ##ascending_sort({random_list})",
            f"The list {lst_str} in increasing order is = ##ascending_sort({random_list})",
            f"The list {lst_str} sorted in non-decreasing order = ##ascending_sort({random_list})",
            f"The sorted form of the list {lst_str} = ##ascending_sort({random_list})",
            f"The value of ascending_sort({lst_str}) is = ##ascending_sort({random_list})",
            f"The outcome of sorting the list {lst_str} is = ##ascending_sort({random_list})",
            f"The ordered arrangement of the numbers in the list {lst_str} = ##ascending_sort({random_list})",
            f"The sorted list of {lst_str} is = ##ascending_sort({random_list})",
            f"The computed sorted list of {lst_str} is = ##ascending_sort({random_list})",
            f"The ordered sequence obtained from sorting the list {lst_str} is = ##ascending_sort({random_list})",
            f"The ascending sorted list of {lst_str} is = ##ascending_sort({random_list})",
            f"The ordered form of the list {lst_str} is = ##ascending_sort({random_list})",
            f"The result of sorting the list {lst_str} is = ##ascending_sort({random_list})",
        ],
        [
            f"The average (mean) of the lst_str {lst_str} = ##average({random_list})",
            f"average({lst_str}) = ##average({random_list})",
            f"The result of calculating the average of the lst_str {lst_str} = ##average({random_list})",
            f"Calculation: average({lst_str}) = ##average({random_list})",
            f"The mean value of the lst_str {lst_str} = ##average({random_list})",
            f"The outcome of finding the average of the lst_str {lst_str} = ##average({random_list})",
            f"The arithmetic mean value of the lst_str {lst_str} = ##average({random_list})",
            f"The result of determining the average of the lst_str {lst_str} = ##average({random_list})",
            f"The computed result of calculating the average of the lst_str {lst_str} = ##average({random_list})",
            f"The average (mean) of the given lst_str {lst_str} = ##average({random_list})",
            f"The outcome of evaluating average({lst_str}) = ##average({random_list})",
            f"The value obtained by calculating the average of the lst_str {lst_str} = ##average({random_list})",
            f"The result of evaluating average({lst_str}) = ##average({random_list})",
            f"The arithmetic mean of the given lst_str {lst_str} = ##average({random_list})",
            f"The computed average value of the lst_str {lst_str} = ##average({random_list})",
            f"The mean value of the given lst_str {lst_str} = ##average({random_list})",
            f"The calculated result of determining the average of the lst_str {lst_str} = ##average({random_list})",
            f"The average (mean) of the lst_str {lst_str} is = ##average({random_list})",
            f"The result derived from calculating the average of the lst_str {lst_str} = ##average({random_list})",
            f"The computed arithmetic mean of the lst_str {lst_str} = ##average({random_list})",
            f"The calculated outcome of evaluating average({lst_str}) = ##average({random_list})",
            f"The computed mean value of the lst_str {lst_str} = ##average({random_list})",
            f"The calculated average value of the lst_str {lst_str} = ##average({random_list})",
            f"The calculated arithmetic mean of the lst_str {lst_str} = ##average({random_list})",
            f"The outcome of finding the arithmetic mean of the lst_str {lst_str} = ##average({random_list})",
            f"The calculated mean value of the lst_str {lst_str} = ##average({random_list})",
            f"The calculated value of the average of the lst_str {lst_str} = ##average({random_list})",
            f"The outcome of evaluating average({lst_str}) = ##average({random_list})",
            f"The outcome of calculating the average value of the lst_str {lst_str} = ##average({random_list})",
        ]
    ]
    return examples[3]
    return random.choice(examples)


if __name__ == "__main__":
    from masked_token_sample_generator import MaskedTokenSamplesGenerator

    masked_example = MaskedTokenSamplesGenerator.create_masked_token_batches(
        get_batch_fifteen_example_paragraph(),
    )
    sample = Utility.create_sample_from_example(
        masked_example,
        PretrainTasks.MASKED_TOKEN_PREDICTION,
    )
    print(sample)

    from next_token_sample_generator import NextTokenSamplesGenerator

    next_token_example = NextTokenSamplesGenerator.create_next_token_batches(
        get_batch_fifteen_example_paragraph(),
    )
    sample = Utility.create_sample_from_example(
        next_token_example,
        PretrainTasks.NEXT_TOKEN_PREDICTION
    )
    print(sample)
